apiVersion: agents.contrastsecurity.com/v1beta1
kind: ClusterAgentConfiguration
metadata:
  name: default-agent-configuration
  namespace: contrast-agent-operator
spec:
  template:
    spec:
      enableYamlVariableReplacement: true
      suppressDefaultApplicationName: false
      suppressDefaultServerName: false
      yaml: |-
        protect:
          enable: true
        assess:
          enable: true
        observe:
          enable: true
        agent:
          logger:
            level: INFO
        application:
          session_metadata: namespace=%namespace%,injector=%annotations.agents.contrastsecurity.com/injector-type%

---